fix 'java.lang.NoClassDefFoundError: org/apache/ivy/core/report/ResolveReport' error that re-appeared when building in Intelli/J after changing to `compileOnly`